### ISSUE TITLE
Remove `TextLintCore` from test code

### ISSUE THREAD

**Issue by azu** [textlint/textlint#1017]
https://github.com/search?q=repo%3Atextlint%2Ftextlint+TextLintCore+path%3A%2F%5Epackages%5C%2Ftextlint%5C%2F%2F+path%3A%2F%5Epackages%5C%2Ftextlint%5C%2Ftest%5C%2F%2F&type=code

`textlint/test` used `TextLintCore`.

Some parts will be remove in v14, others should migrate to @textlint/kernel or new APIs.

## TODO

Migrate to kernel

- [ ] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/pluguins/PluginOption-test.ts#L10
- [ ] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/pluguins/HTMLProcessor-test.ts#L16
- [ ] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/textlint-core/async-rule-test.ts#L5
- [ ] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/rule-tips/rule-tips-after-all-test.ts#L4
- [x] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/rule-context/rule-context-test.ts#L5
- [ ] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/rule-context/rule-context-fixer-test.ts#L3
- [ ] https://github.com/textlint/textlint/blob/5ab6892e6c3f100751542f2c84bc91e78c584f7f/packages/textlint/test/textlint-core/textlint-core-test.ts#L53

## Notes

migrateion script will help it.
https://github.com/textlint/textlint/blob/master/packages/%40textlint/kernel/tools/migrate-core-to-kernel.js

**Comment by azu** [comment]
```js
const path = require("path");
const shell = require("shelljs");
const testRootDirectory = path.join(__dirname, "test");

// textlint.setupRules({}, {}) => const options
function rewriteSetupRuleWithOption() {
    const ruleAndRuleOptionPattern = "textlint.setupRules({ $ruleId: $rule }, { $ruleId: $ruleOption });";
    const ruleAndRuleOptionPatternExpected = `const rule = {
    ruleId: {{ruleId}},
    rule: {{rule}},
    options: {{ruleOption}}
};`;
    shell.exec(
        `npx grasp --in-place -r -e '${ruleAndRuleOptionPattern}' --replace '${ruleAndRuleOptionPatternExpected}' ${testRootDirectory}`
    );
}

// textlint.setupRules({}) => const options
function rewriteSetupRule() {
    const ruleAndRuleOptionPattern = "textlint.setupRules({ $ruleId: $rule });";
    const ruleAndRuleOptionPatternExpected = `const rule = {
    ruleId: {{ruleId}},
    rule: {{rule}}
};`;
    shell.exec(
        `npx grasp --in-place -r -e '${ruleAndRuleOptionPattern}' --replace '${ruleAndRuleOptionPatternExpected}' ${testRootDirectory}`
    );
}

// textlint.setupFilterRules({}, {}) => const options
function rewriteSetupFilterRuleWithOption() {
    const ruleAndRuleOptionPattern = "textlint.setupFilterRules({ $ruleId: $rule }, { $ruleId: $ruleOption });";
    const ruleAndRuleOptionPatternExpected = `const filterRule = {
    ruleId: {{ruleId}},
    rule: {{rule}},
    options: {{ruleOption}}
};`;
    shell.exec(
        `npx grasp --in-place -r -e '${ruleAndRuleOptionPattern}' --replace '${ruleAndRuleOptionPatternExpected}' ${testRootDirectory}`
    );
}

// setupPlugin({}) => const options
function rewriteSetupPlugins() {
    const ruleAndRuleOptionPattern = "textlint.setupPlugins({ $pluginId: $plugin });";
    const ruleAndRuleOptionPatternExpected = `const plugin = {
    pluginId: "{{pluginId}}",
    plugin: {{plugin}},
};`;
    shell.exec(
        `npx grasp --in-place -r -e '${ruleAndRuleOptionPattern}' --replace '${ruleAndRuleOptionPatternExpected}' ${testRootDirectory}`
    );
}

// textlint.setupRules({}) => const options
function rewriteSetupFilterRule() {
    const ruleAndRuleOptionPattern = "textlint.setupFilterRules({ $ruleId: $rule });";
    const ruleAndRuleOptionPatternExpected = `const filterRule = {
    ruleId: {{ruleId}},
    rule: {{rule}}
};`;
    shell.exec(
        `npx grasp --in-place -r -e '${ruleAndRuleOptionPattern}' --replace '${ruleAndRuleOptionPatternExpected}' ${testRootDirectory}`
    );
}

// textlint.lintMarkdown("text") => textlint.lintText(text, options);
function rewriteLintMarkdown() {
    const lintMarkdownPattern = `textlint.lintMarkdown( $text )`;
    const lintMarkdownPatternExpected = `textlint.lintText({{text}}, { ...options, ext: ".md" })`;
    shell.exec(
        `npx grasp --in-place -r -e '${lintMarkdownPattern}' --replace '${lintMarkdownPatternExpected}' ${testRootDirectory}`
    );
}

// textlint.lintFile(filePath) => textlint.lintFile(text, options);
function rewriteLintFile() {
    const pattern = `textlint.lintFile( $filePath )`;
    const expected = `textlint.lintText(fs.readFileSync( {{filePath}}, "utf-8"), { ...options, ext: path.extname({{filePath}}), filePath })`;
    shell.exec(`npx grasp --in-place -r -e '${pattern}' --replace '${expected}' ${testRootDirectory}`);
}

function rewriteCore() {
    const pattern = `textlint = new TextLintCore();`;
    const expected = `textlint = new TextlintKernel()`;
    shell.exec(`npx grasp --in-place -r -e '${pattern}' --replace '${expected}' ${testRootDirectory}`);
}

rewriteSetupRuleWithOption();
rewriteSetupRule();
rewriteSetupFilterRuleWithOption();
rewriteSetupFilterRule();
rewriteSetupPlugins();
rewriteLintMarkdown();
rewriteLintFile()
rewriteCore();

```

**Comment by azu** [comment]
- #1200

**Comment by azu** [comment]
I've tried migrate, but it is difficult.

Probably, we can add new tests instead of migration.



```yaml
# migrate textlint to kernel
#
rules:
  - id: rewriteSetupPlugXXXXX
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    pattern-either:
      - pattern: "$MOD_NAME.setupPlugins({ $pluginId: $plugin });"
      - pattern: "$MOD_NAME.setupPlugins({ $pluginId: $plugin }, { $pluginId: $OPTIONAL_PLUGIN_OPTIONS });"
    fix: |
      const plugins = [{
          pluginId: "$pluginId",
          plugin: $plugin,
          options: $OPTIONAL_PLUGIN_OPTIONS
      }];
    severity: ERROR
  - id: rewriteSetupRuleWithOption
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    pattern-either:
      - pattern: "$MOD_NAME.setupRules({ $RULE_ID: $RULE_IMP })"
      - pattern: "$MOD_NAME.setupRules({ $RULE_ID: $RULE_IMP }, { $RULE_ID: $OPTIONAL_RULE_OPTIONS })"
    fix: |
      const rules = [{
          ruleId: $RULE_ID,
          rule: $RULE_IMP,
          options: $OPTIONAL_RULE_OPTIONS
      }]
    severity: ERROR
  - id: rewriteSetupRule
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: "$MOD_NAME.setupRules({ $ruleId: $rule });"
    fix: |
      const rule = {
          ruleId: $ruleId,
          rule: $rule
      }
    severity: ERROR
  - id: rewriteSetupRule
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    pattern-either:
      - pattern: "$MOD_NAME.setupFilterRules({ $ruleId: $rule });"
      - pattern: "$MOD_NAME.setupFilterRules({ $ruleId: $rule }, { $ruleId: $OPTIONAL_OPT });"
    fix: |
      const filterRule = {
          ruleId: $ruleId,
          rule: $rule,
          options: $OPTIONAL_OPT
      };
    severity: ERROR
  - id: rewriteSetupFilterRule
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: "$MOD_NAME.setupFilterRules({ $ruleId: $rule });"
    fix: |
      const filterRule = {
          ruleId: $ruleId,
          rule: $rule
      };
    severity: ERROR
  - id: rewriteSetupFilterRule
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: $MOD_NAME.lintMarkdown( $text )
    fix: |
      $MOD_NAME.lintText({{text}}, { ...options, ext: ".md" })
    severity: ERROR
  - id: rewriteLintTextExt
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: $MOD_NAME.lintText( $text , "$ext")
    fix: |
      $MOD_NAME.lintText({{text}}, { ...options, ext: "$ext" })
    severity: ERROR
  - id: rewriteLintFile
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: $MOD_NAME.lintFile( $filePath )
    fix: |
      $MOD_NAME.lintText(fs.readFileSync( $filePath, "utf-8"), { ...options, ext: path.extname($filePath), filePath })
    severity: ERROR
  - id: rewriteCore
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: const textlintCore = new TextLintCore()
    fix: |
      const textlintCore = new TextlintKernel()
    severity: ERROR
  - id: rewriteImport
    languages:
      - javascript
    message: |
      Use `new Function` instead of `eval`
    patterns:
      - pattern: import { TextLintCore } from "$IMPORT_PATH"
    fix: |
      import { TextlintKernel } from "@textlint/kernel"
    severity: ERROR

```

**Comment by azu** [comment]
- https://github.com/textlint/textlint/pull/1312

`@textlint/legacy-textlint-core` provide a ponyfill based on kernel
