### ISSUE TITLE
Use "ts-node" filed instea of "ts-node-test-register"

### ISSUE THREAD

**Issue by azu** [textlint/textlint#1044]
https://github.com/textlint/textlint/pull/1043 change this.
Other packages should follow it.

## TODO

- [ ] Remove `ts-node-test-register `
- [ ] Add `ts-node` field in tsconfig
- [ ] Maybe add `"loader": "ts-node/esm"` in tsconfig (It is not work now, but it require in the future)
- [ ] Use `spec` field in mocharc

```diff
❯ git diff HEAD^^
diff --git a/package-lock.json b/package-lock.json
index 7da2fe5fb..49264e8ca 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -32072,7 +32072,6 @@
         "textlint-rule-preset-ja-spacing": "^2.3.0",
         "textlint-rule-preset-jtf-style": "^2.3.13",
         "ts-node": "^10.9.1",
-        "ts-node-test-register": "^10.0.0",
         "typescript": "~4.9.4"
       },
       "engines": {
diff --git a/packages/textlint/.mocharc.json b/packages/textlint/.mocharc.json
index 0a5d627df..831167364 100644
--- a/packages/textlint/.mocharc.json
+++ b/packages/textlint/.mocharc.json
@@ -1,6 +1,7 @@
 {
-  "timeout": "5000",
-  "require": [
-    "ts-node-test-register"
+  "timeout": 5000,
+  "loader": "ts-node/esm",
+  "spec": [
+    "test/*/*.ts"
   ]
 }
diff --git a/packages/textlint/package.json b/packages/textlint/package.json
index af28313a4..0701b0a32 100644
--- a/packages/textlint/package.json
+++ b/packages/textlint/package.json
@@ -42,7 +42,7 @@
         "clean": "rimraf lib/ module/",
         "prepack": "npm run build",
         "test": "npm-run-all test:unit",
-        "test:unit": "mocha \"test/**/*.{js,ts}\"",
+        "test:unit": "mocha",
         "watch": "tsc -b --watch"
     },
     "dependencies": {
@@ -96,7 +96,6 @@
         "textlint-rule-preset-ja-spacing": "^2.3.0",
         "textlint-rule-preset-jtf-style": "^2.3.13",
         "ts-node": "^10.9.1",
-        "ts-node-test-register": "^10.0.0",
         "typescript": "~4.9.4"
     },
     "engines": {
diff --git a/packages/textlint/test/tsconfig.json b/packages/textlint/test/tsconfig.json
deleted file mode 100644
index 018f9a3e8..000000000
--- a/packages/textlint/test/tsconfig.json
+++ /dev/null
@@ -1,16 +0,0 @@
-{
-  "extends": "../tsconfig.json",
-  "compilerOptions": {
-    "noEmit": true,
-    "allowJs": true,
-    "declaration": false,
-  },
-  "include": [
-    "../src/**/*",
-    "./**/*"
-  ],
-  "exclude": [
-    ".git",
-    "node_modules"
-  ]
-}
diff --git a/packages/textlint/tsconfig.json b/packages/textlint/tsconfig.json
index b44ffa228..543ee3b6d 100644
--- a/packages/textlint/tsconfig.json
+++ b/packages/textlint/tsconfig.json
@@ -10,6 +10,15 @@
     ".git",
     "node_modules"
   ],
+  "ts-node": {
+    "compilerOptions": {
+      "noEmit": true,
+      "allowJs": true
+    },
+    "include": [
+      "./**/*"
+    ]
+  },
   "references": [
     {
       "path": "../@textlint/ast-node-types"
```

**Comment by azu** [comment]
> [ ] Use `mocha --forbid-only`

Or just add `forbitOnlyP.
