### ISSUE TITLE
feature: --fix(fixer)

### ISSUE THREAD

**Issue by azu** [textlint/textlint#124]
##We want to support AutoCorrect/Autofixing feature.

- rubocop: https://github.com/bbatsov/rubocop#autocorrect
- ESLint : http://eslint.org/docs/developer-guide/working-with-rules#applying-fixes
     - https://github.com/eslint/eslint/issues/3134
     - https://github.com/eslint/eslint/issues/5329
- JSCS: http://jscs.info/overview

:memo: Have to remember that textlint help you to write texts.
So, textlint's Auto Fixing feature don't bring confusion.

-----
## Implementation

- [x] Initial implementation https://github.com/textlint/textlint/pull/131
- Available [Release 5.5.3: --fix & --experimental support · textlint/textlint](https://github.com/textlint/textlint/releases/tag/5.5.3 "Release 5.5.3: --fix &amp; --experimental support · textlint/textlint") using `--experimental` flag
- Document: [Creating fixable rule](https://github.com/textlint/textlint/blob/master/docs/rule-fixable.md "Creating fixable rule")

### Experimental

When first release, --fix is experimental

```
$ textlint --experimental --fix
```

## TODO :sos: 

- [x] Resonable CLI https://github.com/textlint/textlint-formatter/pull/8

We want to add "How to fix this error?" in linting results.

```sh
$ textlint README.md

...

= How to fix this error
Please do this and fix xxx errors.
$ textlint --fix README.md
```

![result](https://cloud.githubusercontent.com/assets/19714/13637246/ae40bdfa-e649-11e5-8d99-6b342d866a2e.png)

- [ ] How to revert fixed text

In reverse, we should provide the advice "how to rever this changes"?

```sh
$ textlint --fix README.md

...

= How to revert the changes
Please do this and fix xxx errors.
$ git reset HEAD --soft some_file
# or
$ textlint --revert 
```

- [x] Fixer formatter #147  => #148 

Currently, `--fix` formatter is not configuable.
We want to change this to flexiable.

- [x] Separete fixer as module #146 

We'll create textlint-fixer cli.

@azu think that `--fix` is an alias to

```sh
textlint --fix [--formatter nothing-formatter] README.md
# ===
textlint --fix --formatter json README.md | textlint-fixer
```

- [ ] expose [rule-creator-helper.js](https://github.com/textlint/textlint/blob/master/src/rule/rule-creator-helper.js "rule-creator-helper.js")

If you direct use rule modules, non exist correct way now.

- [ ] Update README.md

should add document about  `--fix` usage.

- [x] Add fixable icon to docs

[![textlint rule](https://img.shields.io/badge/textlint-fixable-green.svg?style=social)](https://textlint.github.io/)

**Comment by azu** [comment]
Just idea:

- `linter` : current lint function
- `fixer` :new: is similar with flux utils/Redux's reduce function

```js
export default class MyRule {
    linter(context) {
        context.report({node, fixInfo});
    }

    fixer(prevState, reportResult) {
        switch (result.id) {
            case "MyRule":
                return newState;
            default:
                return prevState;
        }
    }
}
```

**Comment by azu** [comment]
:memo: Rule should talks *protocol*.

Protocol say 

- *found error*
- *found warning*
- *found error* and *fix the error in this way*

**Comment by azu** [comment]
## TODO

- [ ] add fixer `example/`
- [ ] follow update
- [ ] add dcoument
- [ ] add `--experimental` flag

**Comment by azu** [comment]
We'll create `textlint-fixer` cli

```
textlint --fix -f json | textlint-fixer
```

**Comment by azu** [comment]
[5.7.0](https://github.com/textlint/textlint/releases/tag/5.7.0 "5.7.0") contain "Resonable CLI"
