### ISSUE TITLE
textlint 6.0 

### ISSUE THREAD

**Issue by azu** [textlint/textlint#145]
## Breaking Change

**These changes won't affect user.**

-  Remove `TextLintEngine#setRulesBaseDirectory`

Please use

```
new TextLintEngine({
 rulesBaseDirectory: directory
});
```

- Remove `--experimental` flag from `--fix`

`TextLintEngine#fixFiles(files)` and `TextLintEngine# fixText(text, ext = ".txt")` have been removed at 6.0.
It was introduced at [5.5.3: --fix & --experimental support](https://github.com/textlint/textlint/releases/tag/5.5.3 "5.5.3: --fix &amp; --experimental support").

After hard refactoring, `TextLintEngine` was split to `TextFixEngine` and `TextLintEngine`.

Please use `TextFixEngine` instead of above method.

- `TextFixEngine#executeOnFiles(files): TextLintFixResult[]`
- `TextFixEngine#executeOnText(text, evt): TextLintFixResult[]`

FYI: `TextLintEngine` have not changed.

## Features

- Add `TextFixEngine`(ae6aacc)  #146
- Add `TextLintCore#setupProcessors` (76ad42e) #146
- Add `--fix` https://github.com/textlint/textlint/releases/tag/5.5.3
- Add `--dry-run` (9aef49f) #150

### `--fix`

textlint 5.5~ introduces the `--fix` command line argument to automatically fix some rules.

```
$ textlint --fix README.md
# fixed by each rule
```

Not all rules is **fixable**.
So,  it is **difficult** that make all rules **fixable**.

#### What are rules fixable?

[![textlint rule](https://img.shields.io/badge/textlint-fixable-green.svg?style=social)](https://textlint.github.io/) 

- [azu/textlint-rule-prh: textlint rule for prh.](https://github.com/azu/textlint-rule-prh "azu/textlint-rule-prh: textlint rule for prh.")
- [azu/textlint-rule-preset-JTF-style: JTF日本語標準スタイルガイド for textlint.](https://github.com/azu/textlint-rule-preset-JTF-style "azu/textlint-rule-preset-JTF-style: JTF日本語標準スタイルガイド for textlint.")
- [textlint-rule-spellcheck-tech-word](https://github.com/azu/textlint-rule-spellcheck-tech-word "textlint-rule-spellcheck-tech-word")
- [io-monad/textlint-rule-common-misspellings: textlint rule to check common misspellings](https://github.com/io-monad/textlint-rule-common-misspellings)
- [io-monad/textlint-rule-general-novel-style-ja: textlint rule to follow general style of Japanese novels](https://github.com/io-monad/textlint-rule-general-novel-style-ja)
- [nodaguti/textlint-rule-spellchecker: textlint rule to check spellings with native spellchecker](https://github.com/nodaguti/textlint-rule-spellchecker)
- [nodaguti/textlint-rule-ginger: textlint rule to check your English grammar with Ginger Proofreading](https://github.com/nodaguti/textlint-rule-ginger)

You check [textlint/textlint Wiki](https://github.com/textlint/textlint/wiki/Collection-of-textlint-rule "Collection of textlint rule · textlint/textlint Wiki") also.

#### How to create fixable rule?

:information_source:  Please See [Creating fixable rule](https://github.com/textlint/textlint/blob/master/docs/rule-fixable.md "Creating fixable rule") for detail.

#### How to test the rule

Please use [textlint-tester](https://github.com/textlint/textlint-tester "textlint-tester").

- [Release 0.5.1: fixer support · textlint/textlint-tester](https://github.com/textlint/textlint-tester/releases/tag/0.5.1 "Release 0.5.1: fixer support · textlint/textlint-tester")

## TODO

- [x] Update READEM #153 
- [x] Remove `--experimental` from `--fix`  #157
- [x] Publish 6.0 beta 
- [x] Run real world example https://gist.github.com/azu/6d21ebe0efcd7cfd2770
- [x] pull request to linter-textlint https://github.com/1000ch/linter-textlint/pull/20
- [x] pull request to gulp https://github.com/textlint/gulp-textlint/releases/tag/1.2.0
- [x] pull request to Grunt https://github.com/textlint/grunt-textlint/pull/3
- [x] pull reqeust [textlint-tester](https://github.com/textlint/textlint-tester "textlint-tester") https://github.com/textlint/textlint-tester/releases/tag/1.1.0

**Comment by azu** [comment]
[Release 6.0: --fix to be stable · textlint/textlint](https://github.com/textlint/textlint/releases/tag/6.0.1 "Release 6.0: --fix to be stable · textlint/textlint") :tada:

**Comment by azu** [comment]
Completed!

**Comment by azu** [comment]
Close.

I'v write an article in japanese http://efcl.info/2016/03/15/textlint--fix/
