### ISSUE TITLE
textlint 7.0

### ISSUE THREAD

**Issue by azu** [textlint/textlint#184]
Draft for ReleaseNotes

### Filter rule

- "filter rule" support #216 #207 

Filter rule provide filtering error by linting rule.

For example, [textlint-filter-rule-comments](https://github.com/textlint/textlint-filter-rule-comments) provide filtering function by using comments.

```
<!-- textlint-disable -->

Disables all rules between comments

<!-- textlint-enable -->`
```

Allow to short `textlint-filter-rule-comments` to `comments`.

Add filter rule name to `filters` field.

```json
{
  "filters": {
    "comments": true
  }
}
```

One more example, `very-nice-rule` is useful, but you want to ignore some reported error in your text.
`very-nice-rule` also check the `BlockQuote` text, but you want to ignore the `BlockQuote` text.
[textlint-filter-rule-node-types](https://github.com/textlint/textlint-filter-rule-node-types) rule resolve the issue.

```json
{
  "filters": {
    "node-types": {
      "nodeTypes": ["BlockQuote"]
    }
  },
  "rules": {
    "very-nice-rule": true
  }
}
```

###  Sharable Config

* **config:** --config @textlint/textlint-config support ([a059df7](https://github.com/textlint/textlint/commit/a059df7))

See [Sharable Configuration](https://github.com/textlint/textlint/blob/master/docs/configuring.md#sharable-configuration "Sharable Configuration") for details.

Example : [azu/textlint-config-readme: Sharable config for textlint](https://github.com/azu/textlint-config-readme "azu/textlint-config-readme: Sharable config for textlint")

You can use the config via two step.

```
npm i -D @azu/textlint-config-readme textlint
$(npm bin)/textlint --config @azu/textlint-config-readme README.md
```

## Breaking Change

- [x] Ignore duplicated messages by default #209
- [x] Sort messages by line and column #218
      - It only break test case that depended on implementation.
- [ ] <del>Remove deprecated method</del> Still deprecated #183 
      - `loadPlugin`, `loadPreset`, `loadRule`
      - use Constructor options instead of these.
      - But, it is useful for testing.
- [ ] <del>TextLintEngine load config by async </del>
      - https://github.com/davidtheclark/cosmiconfig
      - Add `loadConfig(configFile)`
- [x] Drop Node.js 0.12 support #215

**Comment by azu** [comment]
#194 ignoring rule should be stable in 7.0

**Comment by azu** [comment]
Is `TextLintMessage`.`type` unnnessary? 
It was introduced for ignoring rule #194 But, ignoring rule is renamed to filter rue #212 
`type` is not used...

- https://github.com/textlint/textlint/blob/dae95f781de14a3d987062050ec48d5e55c08d48/typings/textlint.d.ts#L11

**Comment by azu** [comment]
Draft
-----

Draft for ReleaseNotes

## Features

### Filter rule

- "filter rule" support #216 #207 

Filter rule provide filtering error by linting rule.

For example, [textlint-filter-rule-comments](https://github.com/textlint/textlint-filter-rule-comments) provide filtering function by using comments.

```
<!-- textlint-disable -->

Disables all rules between comments

<!-- textlint-enable -->`
```

Allow to short `textlint-filter-rule-comments` to `comments`.

Add filter rule name to `filters` field.

```json
{
  "filters": {
    "comments": true
  }
}
```

One more example, `very-nice-rule` is useful, but you want to ignore some reported error in your text.
`very-nice-rule` also check the `BlockQuote` text, but you want to ignore the `BlockQuote` text.
[textlint-filter-rule-node-types](https://github.com/textlint/textlint-filter-rule-node-types) rule resolve the issue.

```json
{
  "filters": {
    "node-types": {
      "nodeTypes": ["BlockQuote"]
    }
  },
  "rules": {
    "very-nice-rule": true
  }
}
```

###  Sharable Config

* **config:** --config @textlint/textlint-config support ([a059df7](https://github.com/textlint/textlint/commit/a059df7))

See [Sharable Configuration](https://github.com/textlint/textlint/blob/master/docs/configuring.md#sharable-configuration "Sharable Configuration") for details.

Example : [azu/textlint-config-readme: Sharable config for textlint](https://github.com/azu/textlint-config-readme "azu/textlint-config-readme: Sharable config for textlint")

You can use the config via two step.

```
npm i -D @azu/textlint-config-readme textlint
$(npm bin)/textlint --config @azu/textlint-config-readme README.md
```

## Breaking Change

textlint has some breaking change.
It will not affect textlint user, but affect to textlint rule developer.

### Ignore duplicated messages by default #209

Duplicated messages is ignored by default.

Duplicated messages is that have same range and same message.
(Not depended on ruleId. ruleId is flexible property)

### Sort messages by line and column #218

textlint 7.0 sort message by line and column.
The rule that depended on the order of messages may fail test.

### Drop Node.js 0.12 support #215 

textlint 7.0 not support Node.js 0.12. (But still it work)
**Requirement**: Node.js 4.0.0 >=

**Comment by azu** [comment]
Release [7.0.0 beta](https://github.com/textlint/textlint/releases/tag/7.0.0-0 "7.0.0 beta release")

**Comment by azu** [comment]
:shipit: Release https://github.com/textlint/textlint/releases/tag/7.0.0
