### ISSUE TITLE
kernal: export SeverityLevelTypes

### ISSUE THREAD

**Issue by azu** [textlint/textlint#427]
[@textlint/kernel/src/index.ts](https://github.com/textlint/textlint/blob/442c297c60e77de55f07fea7c75d71ac05a6a03a/packages/%40textlint/kernel/src/index.ts "@textlint/kernel/src/index.ts") should export `SeverityLevelTypes` as `TextlintSeverityLevelTypes`.

This type has been removed at "Stop to export unused name #344" @ textlint 10.0.0  #346
Because, no one use it.

But, I've noticed the type is duplication in textlint and kernel.

- https://github.com/textlint/textlint/blob/a144570246d0ec89cbe370f80b5e0706e5c0647a/packages/textlint/src/shared/type/SeverityLevel.ts
- https://github.com/textlint/textlint/blob/c1c2c7ad1d89f9e438d9bc66e89135b7b8cc4615/packages/%40textlint/kernel/src/shared/type/SeverityLevel.ts

We will merge these into `@textlint/kernel`'s `TextlintSeverityLevelTypes`.

## Tasks

- [ ] Make `SeverityLevel` enum
- [ ] [@textlint/kernel/src/index.ts](https://github.com/textlint/textlint/blob/442c297c60e77de55f07fea7c75d71ac05a6a03a/packages/%40textlint/kernel/src/index.ts "@textlint/kernel/src/index.ts") export `SeverityLevel` as `TextlintSeverityLevelTypes`
  - public type has prefix `Textlint*`
- [ ] Remove `SeverityLevel` from `textlint` module
  - Use kernel's `TextlintSeverityLevelTypes` instead of it
  - https://github.com/textlint/textlint/blob/a144570246d0ec89cbe370f80b5e0706e5c0647a/packages/textlint/src/shared/type/SeverityLevel.ts

## question?

Why `SeverityLevel` has `none` and `info`?
This is inspiered by ESLint. But ESLint only has `1` or `2`.

- [Node.js API - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/developer-guide/nodejs-api#linterverify "Node.js API - ESLint - Pluggable JavaScript linter")
