### ISSUE TITLE
Add `clean` npm run-script 

### ISSUE THREAD

**Issue by azu** [textlint/textlint#432]
textlint is monorepo project.
Some [packages](https://github.com/textlint/textlint/tree/master/packages "packages") has not `clean` npm run-script.

## `clean` npm run-script

Basically, `clean` script remove generated files.
Almost packages's `lib/*` is generated files by Babel or TypeScript.
We want to remove that by `clean` scripts.

Examples:

https://github.com/textlint/textlint/blob/4b4509632616736cd7cb01033d08f2fb37bc80f2/packages/%40textlint/kernel/package.json#L19

https://github.com/textlint/textlint/blob/4b4509632616736cd7cb01033d08f2fb37bc80f2/packages/textlint/package.json#L31

## Steps

TBD

- Add `rimraf` to devDeps
- Add `"clean": "rimraf lib/"` 

## Tasks

https://github.com/textlint/textlint/issues/421#issuecomment-353984206 research found following packages has not `clean` scripts.

- [x] `textlint/packages/textlint-ast-test`
- [x] `textlint/packages/@textlint/feature-flag`
- [x] `textlint/packages/txt-ast-traverse`
- [x] `textlint/packages/txt-to-ast`
- [x] `textlint/packages/markdown-to-ast`
- [x] `textlint/packages/textlint-plugin-markdown`
- [x] `textlint/packages/textlint-plugin-text`
- [x] `textlint/packages/textlint-tester`

## Related

 Run "clean" before "test" and "publish" #421

**Comment by azu** [comment]
Tips: `lerna exec` help to resolve this issue.

```sh
./node_modules/.bin/lerna exec "pwd" --scope textlint-ast-test --scope @textlint/feature-flag --scope txt-ast-traverse --scope txt-to-ast --scope markdown-to-ast --scope textlint-plugin-markdown --scope textlint-plugin-text --scope textlint-tester
lerna info version 2.5.1
lerna info versioning independent
lerna info scope [ 'textlint-ast-test',
lerna info scope   '@textlint/feature-flag',
lerna info scope   'txt-ast-traverse',
lerna info scope   'txt-to-ast',
lerna info scope   'markdown-to-ast',
lerna info scope   'textlint-plugin-markdown',
lerna info scope   'textlint-plugin-text',
lerna info scope   'textlint-tester' ]
/Users/azu/.ghq/github.com/textlint/textlint/packages/textlint-ast-test
/Users/azu/.ghq/github.com/textlint/textlint/packages/txt-ast-traverse
/Users/azu/.ghq/github.com/textlint/textlint/packages/@textlint/feature-flag
/Users/azu/.ghq/github.com/textlint/textlint/packages/markdown-to-ast
/Users/azu/.ghq/github.com/textlint/textlint/packages/textlint-tester
/Users/azu/.ghq/github.com/textlint/textlint/packages/txt-to-ast
/Users/azu/.ghq/github.com/textlint/textlint/packages/textlint-plugin-markdown
/Users/azu/.ghq/github.com/textlint/textlint/packages/textlint-plugin-text
```
