### ISSUE TITLE
node type should be exactly

### ISSUE THREAD

**Issue by azu** [textlint/textlint#553]
https://github.com/textlint/textlint/blob/72ae64c1c6352b365f240467e50954303c1b8015/packages/%40textlint/kernel/src/textlint-kernel-interface.ts#L9-L13
https://github.com/textlint/textlint/blob/72ae64c1c6352b365f240467e50954303c1b8015/packages/%40textlint/kernel/src/textlint-kernel-interface.ts#L21-L24

Currently, handler node type is `TxtNode`. That is hard code.
`(node: TxtNode) => void | Promise<any>` 

So, we can not handle type correctly on follwing code.

```ts
        [Syntax.Paragraph](node) {
            if (helper.isChildNode(node, [Syntax.BlockQuote])) {
                return;
            }
            const text = getSource(node);
            // node should be ParentNode, but it is TxtNode
            const sentences = getSentences(node as TxtParentNode);
```

<img width="802" alt="image" src="https://user-images.githubusercontent.com/19714/47782451-9e1c4400-dd43-11e8-915f-67b4a57c26c2.png">

## Tasks

- [ ] Define what node of built-in is [TxtParentNode](https://github.com/textlint/textlint/blob/master/docs/txtnode.md#txtparentnode).
  - `Document`, `Paragraph`...
- [ ] Fix type of parent nodes
- [ ] Undefined node that is specified non-official parser should be `TxtNode`

https://github.com/textlint/textlint/blob/72ae64c1c6352b365f240467e50954303c1b8015/packages/%40textlint/ast-node-types/src/index.ts#L9-L31

**Comment by azu** [comment]
Fixed in #764

**Comment by azu** [comment]
textlint 13 use strict types

[textlint v13.0.0](https://textlint.github.io/blog/2023/01/27/textlint-13.html)+
  - html plugin is written in Pure ESM
