### ISSUE TITLE
Remove ECYCLE Dependency cycles

### ISSUE THREAD

**Issue by azu** [textlint/textlint#567]
Currently, lerna detect Dependency cycles.

We want to reduce the Dependency cycles.

```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE textlint -> @textlint/textlint-plugin-markdown -> textlint
lerna WARN ECYCLE @textlint/ast-tester -> @textlint/markdown-to-ast -> @textlint/ast-tester
lerna WARN ECYCLE @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-tester -> @textlint/markdown-to-ast -> @textlint/markdown-to-ast@^6.1.0
lerna WARN ECYCLE @textlint/types -> @textlint/markdown-to-ast -> @textlint/ast-tester -> @textlint/markdown-to-ast -> @textlint/markdown-to-ast@^6.1.0
lerna WARN ECYCLE @textlint/ast-tester -> @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/markdown-to-ast@^6.1.0
lerna WARN ECYCLE @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-traverse
lerna WARN ECYCLE @textlint/types -> @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/markdown-to-ast@^6.1.0
lerna WARN ECYCLE @textlint/markdown-to-ast -> @textlint/ast-tester -> @textlint/markdown-to-ast
lerna WARN ECYCLE @textlint/text-to-ast -> @textlint/ast-tester -> @textlint/markdown-to-ast -> @textlint/ast-tester -> @textlint/ast-tester@^2.1.0
lerna WARN ECYCLE @textlint/kernel -> @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/ast-traverse@^2.1.0
lerna WARN ECYCLE @textlint/markdown-to-ast -> @textlint/ast-tester -> @textlint/text-to-ast -> @textlint/ast-tester -> @textlint/ast-tester@^2.1.0
lerna WARN ECYCLE @textlint/text-to-ast -> @textlint/ast-tester -> @textlint/text-to-ast
lerna WARN ECYCLE textlint-example-use-as-ts-module -> textlint -> @textlint/textlint-plugin-markdown -> textlint -> textlint@^11.1.0
lerna WARN ECYCLE textlint-tester -> textlint -> @textlint/textlint-plugin-markdown -> textlint -> textlint@^11.1.0
lerna WARN ECYCLE @textlint/textlint-plugin-markdown -> textlint -> @textlint/textlint-plugin-markdown
lerna WARN ECYCLE @textlint/textlint-plugin-text -> textlint -> @textlint/textlint-plugin-markdown -> textlint -> textlint@^11.1.0
lerna WARN ECYCLE textlint-example-use-as-ts-module -> textlint -> @textlint/textlint-plugin-text -> textlint -> textlint@^11.1.0
lerna WARN ECYCLE textlint-tester -> textlint -> @textlint/textlint-plugin-text -> textlint -> textlint@^11.1.0
lerna WARN ECYCLE @textlint/textlint-plugin-markdown -> textlint -> @textlint/textlint-plugin-text -> textlint -> textlint@^11.1.0
lerna WARN ECYCLE @textlint/textlint-plugin-text -> textlint -> @textlint/textlint-plugin-text
```

## Tasks

- [x] `@textlint/textlint-plugin-markdown` should not use `textlint` https://github.com/textlint/textlint/pull/569
  - Use `@textlint/kernel` instead of it
- [x] `@textlint/textlint-plugin-text` should not use `textlint` #571
  - Use `@textlint/kernel` instead of it
- [x] Resolve denependency: @textlint/ast-tester -> @textlint/markdown-to-ast #570 
- [ ] Other?

**Comment by azu** [comment]
rest tasks:
```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-traverse
lerna WARN ECYCLE @textlint/types -> @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/markdown-to-ast@^6.1.0
lerna WARN ECYCLE textlint -> @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/ast-traverse@^2.1.0
lerna WARN ECYCLE @textlint/kernel -> @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/ast-traverse@^2.1.0
lerna WARN ECYCLE @textlint/markdown-to-ast -> @textlint/ast-traverse -> @textlint/markdown-to-ast
```

**Comment by azu** [comment]
Last issue: @textlint/ast-traverse -> @textlint/markdown-to-ast -> @textlint/ast-traverse

Welcome to PR.

**Comment by azu** [comment]
We have done that free Dependency cycles :tada:
