### ISSUE TITLE
Convert to TypeScript again!

### ISSUE THREAD

**Issue by azu** [textlint/textlint#669]
We have conveted core JavaScript packages to TypeScript packages in https://github.com/textlint/textlint/issues/248

But, some packages still use JavaScript.
We want to complete migration from JavaScript to TypeScript.

## Packages

- [x] [textlint/packages/@textlint/markdown-to-ast at master · textlint/textlint](https://github.com/textlint/textlint/tree/master/packages/%40textlint/markdown-to-ast) by @azu #671 
- [x]  [textlint/packages/@textlint/text-to-ast at master · textlint/textlint](https://github.com/textlint/textlint/tree/master/packages/%40textlint/text-to-ast) by @anoriqq #673 
- [x] [textlint/packages/@textlint/textlint-plugin-text at master · textlint/textlint](https://github.com/textlint/textlint/tree/master/packages/%40textlint/textlint-plugin-text) by @Kesin11 #674 
- [x]  [textlint/packages/@textlint/textlint-plugin-markdown at master · textlint/textlint](https://github.com/textlint/textlint/tree/master/packages/%40textlint/textlint-plugin-markdown) by @anoriqq #675 

At first, convert `src/*.js` to `src/*.ts`. Test code use `allowJs` config like https://github.com/textlint/textlint/blob/master/packages/textlint/test/tsconfig.json

Welcome to contribute this migration!

**Blocker**

We are migrating hacky [module resolution](https://github.com/textlint/textlint/issues/440) to Project references #668 

- [x] Use Project References #668

**Comment by azu** [comment]
Add project references usage to https://github.com/textlint/textlint/blob/master/docs/CONTRIBUTING.md#note-typescripts-project-references

**Comment by azu** [comment]
I touch @textlint/markdown-to-ast

**Comment by anoriqq** [comment]
I'm willing to try out this issue!
I'll pick @textlint/text-to-ast up.

**Comment by azu** [comment]
@anoriqq Yeah! Thanks!

I've converted pacakge by following steps in #671 

1. install `typescript ts-node ts-node-test-register` and some `@types/*` pacakges as devDependendencies *1
  - Ref: https://github.com/textlint/textlint/blob/b879a09fb0ba13775cc3d4c83f0b8054e2789f81/packages/%40textlint/markdown-to-ast/package.json#L44-L56
2. Copy `tsconfig.json` to `<pkg>/tsconfig.json`
  - This project use extended `tsconfig.base.json`
  - https://github.com/textlint/textlint/blob/master/packages/%40textlint/markdown-to-ast/tsconfig.json
3. Copy `test/tsconfig.json` to `<pkg>/test/tsconfig.json`
  - Need to add `allowJs: true` at first
  - https://github.com/textlint/textlint/blob/master/packages/%40textlint/markdown-to-ast/test/tsconfig.json
4. Modify mocha.opts to use `--require ts-node-test-register`
  - https://github.com/textlint/textlint/blob/master/packages/%40textlint/markdown-to-ast/test/mocha.opts
5. `yarn run update:projectReferences` on root directory
  - https://github.com/textlint/textlint/blob/master/docs/CONTRIBUTING.md#note-typescripts-project-references
6. Pass `yarn test` on the packages
  - Probably, testings works if `allowJs` is true
7. Convert `src/*.js` to `src/*.ts`
  - I've written articles about this approach in japanses
  - [JavaScriptのライブラリを徐々にTypeScriptに移行する | Web Scratch](https://efcl.info/2017/07/17/javascript-to-typescript/)
  - [Babelで書かれたJavaScriptライブラリをTypeScriptへ移行する方法 | Web Scratch](https://efcl.info/2019/01/09/babel-to-typescript-library/)


<details>
<summary>My convert-to-typescript shellscript *1</summary>
<pre>
#!/bin/bash
# variable
declare scriptDir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
declare currentDir=$(pwd)
declare currentDirName=$(basename "${currentDir}")

# dependecy script
# https://github.com/zeke/npe
if !type npe >/dev/null 2>&1; then
  npm install npe --global
fi
if !type sort-package-json >/dev/null 2>&1; then
  npm install sort-package-json --global
fi
function echo_message(){
  echo "\033[31m=>\033[0m \033[036m$1\033[0m"
}
# Install
echo_message "npm install"
yarn add --dev \
typescript \
ts-node \
ts-node-test-register \
mocha \
@types/node \
@types/mocha \
cross-env
# Copy config
echo_message "Copy .tsconfig mocha.opts"
mkdir -p test
# Edit package.json
## Add script
echo_message "Add npm run-script"
npe scripts.build "cross-env NODE_ENV=production tsc -b."
npe scripts.watch "tsc -b . --watch"
npe scripts.prepublish "npm run --if-present build"
npe scripts.test "mocha \"test/**/*.{js,ts}\""
npe types "lib/${currentDirName}.d.ts"
sort-package-json
# git
git add .
</pre>
</details>

**Comment by anoriqq** [comment]
Thank you for the detailed information. @azu.
It looks like don't need some of the packages listed in step 1. It worked fine with #673.

https://github.com/anoriqq/textlint/blob/dc62bdf2dd7a1a943c5fc30edc9314bb760cc62c/packages/%40textlint/text-to-ast/package.json#L43-L52

Should all packages be installed?

**Comment by azu** [comment]
Ah, naruhodo.
I missed it. I look your PR #673

**Comment by Kesin11** [comment]
I want to try @textlint/textlint-plugin-text 🙋‍♂️

**Comment by anoriqq** [comment]
I touch @textlint/textlint-plugin-markdown

**Comment by azu** [comment]
Now, All core pacakges have been TypeScript!
Thanks for contribution!
