### ISSUE TITLE
[Meta] textlint 12.0.0

### ISSUE THREAD

**Issue by azu** [textlint/textlint#738]
textlint@12.0.0 collection

## Breaking Changes

- [x] All modules use the same version https://github.com/textlint/textlint/issues/676
   - In other words, the next `textlint` and `@textlint/*` will be v12.0.0
- [x] textlint-tester export as default #689 
- [x] Drop Node.js 10 support https://github.com/textlint/textlint/issues/600
- [x] Update remark #717 
- [x] update textlitnt-scripts@4

**Comment by azu** [comment]
## @textlint/markdown-to-ast

It is a markdown parser in textlint.
We have updated to remark@13.0.0 #717 and it has many changes for Markdown AST

You can see the changes at [feat(markdown-to-ast): update to remark-parse@9 #767](https://github.com/textlint/textlint/pull/767)

### Features

#### Add `FootnoteReference` node

```markdown
The NATO phonetic alphabet[^wiki].

[^wiki]: Read more about it on wikipedia: <http://en.wikipedia.org/wiki/NATO_phonetic_alphabet>.
```

Previously, It is called `LinkReference`, textlint@12 treat it as `FootnoteReference`.

### Known bugs

- [x] gfm parsing bug that generate broken AST: https://github.com/remarkjs/remark-gfm/issues/16
	- → use workaround:  https://github.com/remarkjs/remark-gfm/issues/16#issuecomment-846357030 at https://github.com/textlint/textlint/commit/c99218ea37518e8a42bb5d283276ccf696618748
	- → markdown-to-ast does not generate broken AST.

**Comment by azu** [comment]
## 12.0.0-beta.0 #778 

```
npm install textlint@beta
```

**Comment by azu** [comment]
## 12.0.0-beta.1 #780 

textlint user

```
npm install textlint@beta
```

Rule creator

```
npm install textlint-script@beta
```

**Comment by azu** [comment]
I found an error on textlint-plugin-asciidoctor.

- https://github.com/seikichi/textlint-plugin-asciidoctor/issues/18

However, it is not related 12.0.0 directory.
It is affected by #649 and we mitigate the effects in #783

**Comment by azu** [comment]
##  v12.0.0-beta.2 #785 

textlint user

```
npm install textlint@beta
```

textlint rule creator

```
npm install textlint-scripts@beta
```

Next will be stable releases.

**Comment by azu** [comment]
#786

**Comment by azu** [comment]
After release

- [ ] update template repo

**Comment by azu** [comment]
https://textlint.github.io/blog/2021/05/24/textlint-12.html Released 🎉

**Comment by azu** [comment]
https://textlint.github.io/astexplorer/#/snippet/woXCqHBhcnNlcklEwrh0ZXh0bGludDptxINrZG93bi10by1hc3TCqMSFdHTEkGdzwoHEisSMxI7EkMSSxJRyxJbEmMSaxJzEnsSgw4DCqHbEhnNpb27EqMSqxI3Ej8SRxJPElcSXxJnEm8SdxJ90wqYxMi4wxY_CqGZpbGVuYW1lwrBzb3VyY2UudW5kZcWTbmVkwqRjb8Wlw5lNIyBUacSOZQoKVGhpcyDFuyDEi8SNLsW3LSDEj8Sgxb3Ei23Ft1tMxJBrXShoxKRwOi8vxIzFmHDFlS7FrG0pxoMgU2HEuWTFv8Sr}

Update AST Explorer and support "Save"

**Comment by azu** [comment]
Complete!

**Comment by azu** [comment]
→ [textlint v12.0.0 released! · Discussion #789 · textlint/textlint](https://github.com/textlint/textlint/discussions/789)
