### ISSUE TITLE
Move to npm 8+

### ISSUE THREAD

**Issue by azu** [textlint/textlint#989]
yarn v1 fails at sometimes.
https://github.com/textlint/textlint/pull/988#issuecomment-1376768712
We have used cache, but yarn fail to fetch
https://github.com/textlint/textlint/blob/ca4fda9464d209df510bbd3db94b3054cab67701/.github/workflows/ci.yml#L20

Yarn v1 will not fix these issues.

- https://github.com/yarnpkg/yarn/issues/7734
- https://github.com/yarnpkg/yarn/issues/8242

We can move to npm 8+. Now is the time.

## TODO

- [ ] remove yarn.lock
- [ ] add package-lock.json
- [ ] change lerna.json to `npm`
  - https://github.com/textlint/textlint/blob/ca4fda9464d209df510bbd3db94b3054cab67701/lerna.json#L3-L6
- [ ] Replace `yarn` to `npm` command in [CI](https://github.com/textlint/textlint/tree/master/.github/workflows) and [`scripts`](https://github.com/textlint/textlint/tree/master/.github/workflows) ant [netlify.yml](https://github.com/textlint/textlint/blob/master/netlify.toml) etc...
- [ ] Rewrite [CONTRIBUTING.md](https://github.com/textlint/textlint/blob/master/docs/CONTRIBUTING.md)

## Test Plans

- [ ] Pass CI
- [ ] grep yarn
  - [rg](https://github.com/BurntSushi/ripgrep) is useful
